/**
 * The opt-in database layer: which engines can be chosen, and what each stack
 * needs in order to talk to them.
 *
 * Every stack ends up with the same shape — a model, a repository or client,
 * and a worked GET/POST /api/items — reached through whichever ORM is native
 * to that language: Prisma for TypeScript, SQLAlchemy for Python, Spring Data
 * JPA for Java. The connection string always comes from DATABASE_URL, so the
 * variable name is the same wherever you look.
 */

import type { ComposeService, LayerPlan, MavenDependency } from "./layers.js";
import type { Stack } from "./stacks.js";

export const DATABASES = ["none", "sqlite", "postgres", "mysql", "mongodb"] as const;
export type Database = (typeof DATABASES)[number];

/** Every database except "none", which means "don't scaffold a layer at all". */
export type Engine = Exclude<Database, "none">;

/**
 * The engines reached through a SQL ORM. MongoDB is the odd one out: Prisma
 * speaks it, but SQLAlchemy and JPA do not, so those two stacks get their own
 * client and their own templates rather than a driver swap.
 */
type SqlEngine = Exclude<Engine, "mongodb">;

export const DATABASE_LABELS: Record<Database, string> = {
  none: "None — add one later",
  sqlite: "SQLite — a file, nothing to install",
  postgres: "PostgreSQL — also Supabase, Neon, RDS",
  mysql: "MySQL or MariaDB",
  mongodb: "MongoDB — documents, not tables",
};

export function isEngine(database: Database): database is Engine {
  return database !== "none";
}

/** The connection string every MongoDB stack starts from. */
const MONGO_URL = "mongodb://localhost:27017/__PROJECT_NAME__";

/**
 * Prisma's provider name, a starting DATABASE_URL, and the model's id field —
 * the one line of schema.prisma that a document database changes, since an
 * ObjectId is neither an integer nor generated by the database's own counter.
 */
const RELATIONAL_ID = "Int      @id @default(autoincrement())";

const PRISMA: Record<Engine, { provider: string; url: string; id: string }> = {
  sqlite: { provider: "sqlite", url: "file:./dev.db", id: RELATIONAL_ID },
  postgres: {
    provider: "postgresql",
    url: "postgresql://postgres:postgres@localhost:5432/__PROJECT_NAME__",
    id: RELATIONAL_ID,
  },
  mysql: {
    provider: "mysql",
    url: "mysql://root:root@localhost:3306/__PROJECT_NAME__",
    id: RELATIONAL_ID,
  },
  mongodb: {
    provider: "mongodb",
    url: MONGO_URL,
    id: 'String   @id @default(auto()) @map("_id") @db.ObjectId',
  },
};

/** SQLAlchemy URLs, and the driver each one needs on top of SQLAlchemy. */
const SQLALCHEMY: Record<SqlEngine, { url: string; requirements: string[] }> = {
  sqlite: { url: "sqlite:///./dev.db", requirements: [] },
  postgres: {
    url: "postgresql+psycopg://postgres:postgres@localhost:5432/__PROJECT_NAME__",
    requirements: ["psycopg[binary]>=3.2"],
  },
  mysql: {
    url: "mysql+pymysql://root:root@localhost:3306/__PROJECT_NAME__",
    // MySQL 8 authenticates with caching_sha2_password by default, and PyMySQL
    // can only complete that handshake with cryptography installed.
    requirements: ["PyMySQL>=1.1", "cryptography>=43.0"],
  },
};

/**
 * JDBC settings per engine. SQLite has no Hibernate dialect in the core
 * distribution, so it also pulls in the community dialects module — the same
 * arrangement Spring's own SQLite guides use.
 *
 * JDBC is the one place where the user and password are not part of the URL,
 * so they travel as their own variables. They go in `.env` next to
 * DATABASE_URL rather than only in application.properties: a JDBC URL is
 * where someone editing their connection expects to find everything about it,
 * and defaults nothing mentions are defaults nobody can change.
 */
const JDBC: Record<
  SqlEngine,
  {
    url: string;
    driver: MavenDependency;
    credentials?: Record<string, string>;
    properties: Record<string, string>;
  }
> = {
  sqlite: {
    url: "jdbc:sqlite:./dev.db",
    driver: { groupId: "org.xerial", artifactId: "sqlite-jdbc" },
    properties: {
      "spring.jpa.properties.hibernate.dialect":
        "org.hibernate.community.dialect.SQLiteDialect",
    },
  },
  postgres: {
    url: "jdbc:postgresql://localhost:5432/__PROJECT_NAME__",
    driver: { groupId: "org.postgresql", artifactId: "postgresql", scope: "runtime" },
    credentials: { DATABASE_USER: "postgres", DATABASE_PASSWORD: "postgres" },
    properties: {
      "spring.datasource.username": "${DATABASE_USER:postgres}",
      "spring.datasource.password": "${DATABASE_PASSWORD:postgres}",
    },
  },
  mysql: {
    url: "jdbc:mysql://localhost:3306/__PROJECT_NAME__",
    driver: { groupId: "com.mysql", artifactId: "mysql-connector-j", scope: "runtime" },
    credentials: { DATABASE_USER: "root", DATABASE_PASSWORD: "root" },
    properties: {
      "spring.datasource.username": "${DATABASE_USER:root}",
      "spring.datasource.password": "${DATABASE_PASSWORD:root}",
    },
  },
};

const EXTRA_SQLITE_JAVA: MavenDependency = {
  groupId: "org.hibernate.orm",
  artifactId: "hibernate-community-dialects",
};

const PRISMA_VERSION = "^6.2.0";

/**
 * Where each stack's SQLite file actually lands. Prisma resolves a relative
 * url against the schema's directory, while SQLAlchemy and JDBC resolve it
 * against the process's working directory — which is the server folder.
 */
const SQLITE_IGNORES: Record<Stack, string[]> = {
  typescript: ["", "# Database", "server/prisma/dev.db", "server/prisma/dev.db-journal"],
  nextjs: ["", "# Database", "prisma/dev.db", "prisma/dev.db-journal"],
  python: ["", "# Database", "server/dev.db", "server/dev.db-journal"],
  springboot: ["", "# Database", "server/dev.db", "server/dev.db-journal"],
};

/**
 * Prisma is the one ORM here that won't create its tables on first start, so
 * every Prisma project needs `db:push` run once before `POST /api/items` can
 * work. SQLite has no server to wait for and can do it during install; the
 * others can only be pushed to once the developer has a database up, so the
 * command is printed instead of run.
 *
 * SQLAlchemy and Hibernate need neither: `create_tables()` and
 * `ddl-auto=update` cover the same ground on startup.
 */
function schemaPush(
  engine: Engine,
  command: string
): Pick<LayerPlan, "installStep" | "manualStep"> {
  if (engine === "sqlite") return { installStep: command };
  const made = engine === "mongodb" ? "the collections and indexes" : "the tables";
  return {
    manualStep: { command, reason: `creates ${made}, once your database is reachable` },
  };
}

const ENGINE_NAMES: Record<Engine, string> = {
  sqlite: "SQLite",
  postgres: "Postgres",
  mysql: "MySQL",
  mongodb: "MongoDB",
};

/**
 * The server each engine needs running, as a service in the project's compose
 * file. SQLite is a file and needs none.
 */
const DATABASE_SERVICE: Record<Engine, ComposeService | undefined> = {
  sqlite: undefined,
  postgres: { fragment: "postgres", label: "Postgres", volume: "db-data" },
  mysql: { fragment: "mysql", label: "MySQL", volume: "db-data" },
  mongodb: { fragment: "mongodb", label: "MongoDB", volume: "db-data" },
};

/** The library each stack reaches its database through, by name. */
function ormName(stack: Stack, engine: Engine): string {
  if (engine === "mongodb") {
    return { typescript: "Prisma", nextjs: "Prisma", python: "PyMongo", springboot: "Spring Data MongoDB" }[
      stack
    ];
  }
  return { typescript: "Prisma", nextjs: "Prisma", python: "SQLAlchemy", springboot: "Spring Data JPA" }[
    stack
  ];
}

/**
 * The section the layer adds to the project's own README: where the connection
 * string lives, the commands that drive the database, and what the worked
 * example is for. `push` is the Prisma command, on the stacks that have one.
 */
function readmeSection(stack: Stack, engine: Engine, push?: string): string[] {
  const envFile = stack === "nextjs" ? "`.env`" : "`server/.env`";
  const lines = ["", "## Database", ""];

  lines.push(
    ...(engine === "sqlite"
      ? [
          `${ENGINE_NAMES[engine]}, through ${ormName(stack, engine)}. The database is a`,
          `single file, named by \`DATABASE_URL\` in ${envFile}.`,
        ]
      : [
          `${ENGINE_NAMES[engine]}, through ${ormName(stack, engine)}. The connection string is`,
          `\`DATABASE_URL\` in ${envFile} — point it at a hosted database and the`,
          "code follows it there.",
        ])
  );

  if (stack === "springboot") {
    lines.push(
      "",
      "A JDBC URL carries no credentials, so Spring reads `DATABASE_USER` and",
      "`DATABASE_PASSWORD` from the same file."
    );
  }

  const commands: [string, string][] = [];
  if (engine !== "sqlite") {
    commands.push(["npm run docker:up", `start ${ENGINE_NAMES[engine]} in Docker, on that URL`]);
  }
  const rows = engine === "mongodb" ? "collections" : "tables";
  if (push) {
    commands.push([push, `create or update the ${rows}`]);
  }
  if (engine !== "sqlite") {
    commands.push(["npm run docker:down", "stop it; your data stays in the volume"]);
  }
  if (commands.length > 0) {
    const width = Math.max(...commands.map(([command]) => command.length));
    lines.push(
      "",
      "```bash",
      ...commands.map(([command, note]) => `${command.padEnd(width)}   # ${note}`),
      "```"
    );
  }

  lines.push(
    "",
    push
      ? `The schema lives in \`schema.prisma\`; the ${rows} follow it on \`db:push\`.`
      : `The ${rows} are created on startup from the models, so there is no migration step.`,
    "",
    "`GET /api/items` and `POST /api/items` are a worked example against the",
    "`Item` model. Copy the shape you need, then delete it."
  );

  return lines;
}

/**
 * Which directory under templates/databases holds the layer's files. Prisma
 * speaks MongoDB with the same client API it uses for SQL, so those two stacks
 * keep one set of templates; SQLAlchemy and JPA don't, so those two have a
 * second set written against the document database instead.
 */
export function databaseTemplate(stack: Stack, engine: Engine): string {
  const sameEitherWay = stack === "typescript" || stack === "nextjs";
  return engine === "mongodb" && !sameEitherWay ? `mongodb/${stack}` : stack;
}

export function planDatabase(stack: Stack, engine: Engine): LayerPlan {
  switch (stack) {
    case "typescript":
      return {
        envHeading: "# Database",
        env: { DATABASE_URL: PRISMA[engine].url },
        replacements: {
          __DB_PROVIDER__: PRISMA[engine].provider,
          __DB_ID__: PRISMA[engine].id,
        },
        compose: DATABASE_SERVICE[engine],
        packageJson: {
          path: "server/package.json",
          dependencies: { "@prisma/client": PRISMA_VERSION },
          devDependencies: { prisma: PRISMA_VERSION },
          scripts: {
            postinstall: "prisma generate",
            "db:push": "prisma db push",
            "db:studio": "prisma studio",
          },
        },
        wiring: {
          path: "server/src/index.ts",
          imports: ['import { items } from "./items.js";'],
          routes: ["app.use(items);"],
        },
        ...schemaPush(engine, "npm run db:push --prefix server"),
        gitignore: engine === "sqlite" ? SQLITE_IGNORES.typescript : undefined,
        readme: {
          path: "README.md",
          lines: readmeSection(stack, engine, "npm run db:push --prefix server"),
        },
      };

    case "nextjs":
      return {
        envHeading: "# Database",
        env: { DATABASE_URL: PRISMA[engine].url },
        replacements: {
          __DB_PROVIDER__: PRISMA[engine].provider,
          __DB_ID__: PRISMA[engine].id,
        },
        compose: DATABASE_SERVICE[engine],
        packageJson: {
          path: "package.json",
          dependencies: { "@prisma/client": PRISMA_VERSION },
          devDependencies: { prisma: PRISMA_VERSION },
          scripts: {
            postinstall: "prisma generate",
            "db:push": "prisma db push",
            "db:studio": "prisma studio",
          },
        },
        ...schemaPush(engine, "npm run db:push"),
        gitignore: engine === "sqlite" ? SQLITE_IGNORES.nextjs : undefined,
        readme: { path: "README.md", lines: readmeSection(stack, engine, "npm run db:push") },
      };

    case "python":
      if (engine === "mongodb") {
        return {
          envHeading: "# Database",
          env: { DATABASE_URL: MONGO_URL },
          replacements: { __DB_URL__: MONGO_URL },
          compose: DATABASE_SERVICE[engine],
          requirements: { path: "server/requirements.txt", lines: ["pymongo>=4.9"] },
          wiring: {
            path: "server/main.py",
            imports: ["from db import create_indexes", "from items import router as items_router"],
            routes: ["create_indexes()", "app.include_router(items_router)"],
          },
          readme: { path: "README.md", lines: readmeSection(stack, engine) },
        };
      }
      return {
        envHeading: "# Database",
        env: { DATABASE_URL: SQLALCHEMY[engine].url },
        compose: DATABASE_SERVICE[engine],
        replacements: { __DB_URL__: SQLALCHEMY[engine].url },
        requirements: {
          path: "server/requirements.txt",
          lines: ["sqlalchemy>=2.0", ...SQLALCHEMY[engine].requirements],
        },
        wiring: {
          path: "server/main.py",
          imports: ["from db import create_tables", "from items import router as items_router"],
          routes: ["create_tables()", "app.include_router(items_router)"],
        },
        gitignore: engine === "sqlite" ? SQLITE_IGNORES.python : undefined,
        readme: { path: "README.md", lines: readmeSection(stack, engine) },
      };

    case "springboot":
      if (engine === "mongodb") {
        return {
          envHeading: "# Database",
          env: { DATABASE_URL: MONGO_URL },
          compose: DATABASE_SERVICE[engine],
          maven: {
            path: "server/pom.xml",
            dependencies: [
              {
                groupId: "org.springframework.boot",
                artifactId: "spring-boot-starter-data-mongodb",
              },
            ],
          },
          properties: {
            path: "server/src/main/resources/application.properties",
            heading: "# Database",
            entries: {
              "spring.data.mongodb.uri": "${DATABASE_URL:" + MONGO_URL + "}",
              // JPA creates its schema from the entities; Mongo's equivalent
              // is off by default, and @Indexed does nothing without it.
              "spring.data.mongodb.auto-index-creation": "true",
            },
          },
          readme: { path: "README.md", lines: readmeSection(stack, engine) },
        };
      }
      return {
        envHeading: "# Database",
        env: { DATABASE_URL: JDBC[engine].url, ...JDBC[engine].credentials },
        compose: DATABASE_SERVICE[engine],
        maven: {
          path: "server/pom.xml",
          dependencies: [
            { groupId: "org.springframework.boot", artifactId: "spring-boot-starter-data-jpa" },
            JDBC[engine].driver,
            ...(engine === "sqlite" ? [EXTRA_SQLITE_JAVA] : []),
          ],
        },
        properties: {
          path: "server/src/main/resources/application.properties",
          heading: "# Database",
          entries: {
            "spring.datasource.url": "${DATABASE_URL:" + JDBC[engine].url + "}",
            "spring.jpa.hibernate.ddl-auto": "update",
            "spring.jpa.open-in-view": "false",
            ...JDBC[engine].properties,
          },
        },
        gitignore: engine === "sqlite" ? SQLITE_IGNORES.springboot : undefined,
        readme: { path: "README.md", lines: readmeSection(stack, engine) },
      };
  }
}
